BEGIN;

CREATE TABLE IF NOT EXISTS exercise (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(280) NOT NULL
);

CREATE TABLE IF NOT EXISTS equipment (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(280) NOT NULL
);

CREATE TABLE IF NOT EXISTS muscle_group (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(280) NOT NULL
);

CREATE TABLE IF NOT EXISTS video (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(300) NOT NULL,
    url VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS image (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(300) NOT NULL,
    url VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS exercise_equipment (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    exercise_id INT NOT NULL REFERENCES exercise,
    equipment_id INT NOT NULL REFERENCES equipment
);

CREATE TABLE IF NOT EXISTS exercise_muscle_group (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    exercise_id INT NOT NULL REFERENCES exercise,
    muscle_group_id INT NOT NULL REFERENCES muscle_group
);

CREATE TABLE IF NOT EXISTS exercise_video (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    exercise_id INT NOT NULL REFERENCES exercise,
    video_id INT NOT NULL REFERENCES video
);

CREATE TABLE IF NOT EXISTS exercise_image (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    exercise_id INT NOT NULL REFERENCES exercise,
    image_id INT NOT NULL REFERENCES image
);

COMMIT;